services:
  certbot_init:
    image: certbot:local
    container_name: certbot_init
    volumes:
      - ${BIND_VOLUMES}/nginx/certs_data:/etc/letsencrypt
      - ${BIND_VOLUMES}/nginx/certbot_www:/var/www/certbot
    entrypoint: /bin/sh -c "
      if [ ! -f /etc/letsencrypt/live/abc8888.ru/fullchain.pem ]; then
        certbot certonly --standalone \
        --non-interactive --agree-tos --email admin@abc8888.ru \
        -d abc8888.ru \
        -d api.abc8888.ru \
        -d test.abc8888.ru \
        -d kan.abc8888.ru \
        -d api.test.abc8888.ru;
      else
        certbot renew --webroot --webroot-path=/var/www/certbot --quiet;
      fi"
    ports:
      - "80:80"
    networks:
      shared_network:
        ipv4_address: ${IP_NGINX}

  nginx_gateway:
    image: nginx:local
    container_name: nginx_gateway
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ${BIND_VOLUMES}/nginx/static:/etc/nginx/static:ro
      - ${BIND_VOLUMES}/nginx/certs_data:/etc/letsencrypt
      - ${BIND_VOLUMES}/nginx/certbot_www:/var/www/certbot
      - ${BIND_VOLUMES}/nginx/.htpasswd:/etc/nginx/.htpasswd:ro
      - ./nginx/static:/etc/nginx/static:ro
    networks:
      shared_network:
        ipv4_address: ${IP_NGINX}
    depends_on:
      certbot_init:
        condition: service_completed_successfully
    command: /bin/sh -c "echo '0 12 * * * certbot renew --quiet --post-hook \"nginx -s reload\"' > /etc/crontabs/root && crond && nginx -g 'daemon off;'"

networks:
  shared_network:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET_NGINX}

volumes:
  certs_data:
  certbot_www:
