# Общие правила для отдачи robots.txt на всех доменах
location = /robots.txt {
    root /etc/nginx/static;
    access_log off;
    log_not_found off;

    # Дополнительно: принудительно задаю правильный тип (на случай сбоев MIME)
    default_type text/plain;
}
